# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from function import dex_api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DexStub:
    """Dex represents the dex gRPC service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClient = channel.unary_unary(
                '/api.Dex/GetClient',
                request_serializer=api__pb2.GetClientReq.SerializeToString,
                response_deserializer=api__pb2.GetClientResp.FromString,
                _registered_method=True)
        self.CreateClient = channel.unary_unary(
                '/api.Dex/CreateClient',
                request_serializer=api__pb2.CreateClientReq.SerializeToString,
                response_deserializer=api__pb2.CreateClientResp.FromString,
                _registered_method=True)
        self.UpdateClient = channel.unary_unary(
                '/api.Dex/UpdateClient',
                request_serializer=api__pb2.UpdateClientReq.SerializeToString,
                response_deserializer=api__pb2.UpdateClientResp.FromString,
                _registered_method=True)
        self.DeleteClient = channel.unary_unary(
                '/api.Dex/DeleteClient',
                request_serializer=api__pb2.DeleteClientReq.SerializeToString,
                response_deserializer=api__pb2.DeleteClientResp.FromString,
                _registered_method=True)
        self.ListClients = channel.unary_unary(
                '/api.Dex/ListClients',
                request_serializer=api__pb2.ListClientReq.SerializeToString,
                response_deserializer=api__pb2.ListClientResp.FromString,
                _registered_method=True)
        self.CreatePassword = channel.unary_unary(
                '/api.Dex/CreatePassword',
                request_serializer=api__pb2.CreatePasswordReq.SerializeToString,
                response_deserializer=api__pb2.CreatePasswordResp.FromString,
                _registered_method=True)
        self.UpdatePassword = channel.unary_unary(
                '/api.Dex/UpdatePassword',
                request_serializer=api__pb2.UpdatePasswordReq.SerializeToString,
                response_deserializer=api__pb2.UpdatePasswordResp.FromString,
                _registered_method=True)
        self.DeletePassword = channel.unary_unary(
                '/api.Dex/DeletePassword',
                request_serializer=api__pb2.DeletePasswordReq.SerializeToString,
                response_deserializer=api__pb2.DeletePasswordResp.FromString,
                _registered_method=True)
        self.ListPasswords = channel.unary_unary(
                '/api.Dex/ListPasswords',
                request_serializer=api__pb2.ListPasswordReq.SerializeToString,
                response_deserializer=api__pb2.ListPasswordResp.FromString,
                _registered_method=True)
        self.CreateConnector = channel.unary_unary(
                '/api.Dex/CreateConnector',
                request_serializer=api__pb2.CreateConnectorReq.SerializeToString,
                response_deserializer=api__pb2.CreateConnectorResp.FromString,
                _registered_method=True)
        self.UpdateConnector = channel.unary_unary(
                '/api.Dex/UpdateConnector',
                request_serializer=api__pb2.UpdateConnectorReq.SerializeToString,
                response_deserializer=api__pb2.UpdateConnectorResp.FromString,
                _registered_method=True)
        self.DeleteConnector = channel.unary_unary(
                '/api.Dex/DeleteConnector',
                request_serializer=api__pb2.DeleteConnectorReq.SerializeToString,
                response_deserializer=api__pb2.DeleteConnectorResp.FromString,
                _registered_method=True)
        self.ListConnectors = channel.unary_unary(
                '/api.Dex/ListConnectors',
                request_serializer=api__pb2.ListConnectorReq.SerializeToString,
                response_deserializer=api__pb2.ListConnectorResp.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/api.Dex/GetVersion',
                request_serializer=api__pb2.VersionReq.SerializeToString,
                response_deserializer=api__pb2.VersionResp.FromString,
                _registered_method=True)
        self.GetDiscovery = channel.unary_unary(
                '/api.Dex/GetDiscovery',
                request_serializer=api__pb2.DiscoveryReq.SerializeToString,
                response_deserializer=api__pb2.DiscoveryResp.FromString,
                _registered_method=True)
        self.ListRefresh = channel.unary_unary(
                '/api.Dex/ListRefresh',
                request_serializer=api__pb2.ListRefreshReq.SerializeToString,
                response_deserializer=api__pb2.ListRefreshResp.FromString,
                _registered_method=True)
        self.RevokeRefresh = channel.unary_unary(
                '/api.Dex/RevokeRefresh',
                request_serializer=api__pb2.RevokeRefreshReq.SerializeToString,
                response_deserializer=api__pb2.RevokeRefreshResp.FromString,
                _registered_method=True)
        self.VerifyPassword = channel.unary_unary(
                '/api.Dex/VerifyPassword',
                request_serializer=api__pb2.VerifyPasswordReq.SerializeToString,
                response_deserializer=api__pb2.VerifyPasswordResp.FromString,
                _registered_method=True)
        self.GetAuthSession = channel.unary_unary(
                '/api.Dex/GetAuthSession',
                request_serializer=api__pb2.GetAuthSessionReq.SerializeToString,
                response_deserializer=api__pb2.GetAuthSessionResp.FromString,
                _registered_method=True)
        self.ListAuthSessions = channel.unary_unary(
                '/api.Dex/ListAuthSessions',
                request_serializer=api__pb2.ListAuthSessionsReq.SerializeToString,
                response_deserializer=api__pb2.ListAuthSessionsResp.FromString,
                _registered_method=True)
        self.DeleteAuthSession = channel.unary_unary(
                '/api.Dex/DeleteAuthSession',
                request_serializer=api__pb2.DeleteAuthSessionReq.SerializeToString,
                response_deserializer=api__pb2.DeleteAuthSessionResp.FromString,
                _registered_method=True)
        self.TerminateSessionsByConnector = channel.unary_unary(
                '/api.Dex/TerminateSessionsByConnector',
                request_serializer=api__pb2.TerminateSessionsByConnectorReq.SerializeToString,
                response_deserializer=api__pb2.TerminateSessionsByConnectorResp.FromString,
                _registered_method=True)
        self.TerminateSessionsByUser = channel.unary_unary(
                '/api.Dex/TerminateSessionsByUser',
                request_serializer=api__pb2.TerminateSessionsByUserReq.SerializeToString,
                response_deserializer=api__pb2.TerminateSessionsByUserResp.FromString,
                _registered_method=True)
        self.GetUserIdentity = channel.unary_unary(
                '/api.Dex/GetUserIdentity',
                request_serializer=api__pb2.GetUserIdentityReq.SerializeToString,
                response_deserializer=api__pb2.GetUserIdentityResp.FromString,
                _registered_method=True)
        self.ListUserIdentities = channel.unary_unary(
                '/api.Dex/ListUserIdentities',
                request_serializer=api__pb2.ListUserIdentitiesReq.SerializeToString,
                response_deserializer=api__pb2.ListUserIdentitiesResp.FromString,
                _registered_method=True)
        self.DeleteUserIdentity = channel.unary_unary(
                '/api.Dex/DeleteUserIdentity',
                request_serializer=api__pb2.DeleteUserIdentityReq.SerializeToString,
                response_deserializer=api__pb2.DeleteUserIdentityResp.FromString,
                _registered_method=True)
        self.ResetMFA = channel.unary_unary(
                '/api.Dex/ResetMFA',
                request_serializer=api__pb2.ResetMFAReq.SerializeToString,
                response_deserializer=api__pb2.ResetMFAResp.FromString,
                _registered_method=True)
        self.ListMFADevices = channel.unary_unary(
                '/api.Dex/ListMFADevices',
                request_serializer=api__pb2.ListMFADevicesReq.SerializeToString,
                response_deserializer=api__pb2.ListMFADevicesResp.FromString,
                _registered_method=True)
        self.DeleteWebAuthnCredential = channel.unary_unary(
                '/api.Dex/DeleteWebAuthnCredential',
                request_serializer=api__pb2.DeleteWebAuthnCredentialReq.SerializeToString,
                response_deserializer=api__pb2.DeleteWebAuthnCredentialResp.FromString,
                _registered_method=True)
        self.DeleteMFASecret = channel.unary_unary(
                '/api.Dex/DeleteMFASecret',
                request_serializer=api__pb2.DeleteMFASecretReq.SerializeToString,
                response_deserializer=api__pb2.DeleteMFASecretResp.FromString,
                _registered_method=True)
        self.RevokeConsent = channel.unary_unary(
                '/api.Dex/RevokeConsent',
                request_serializer=api__pb2.RevokeConsentReq.SerializeToString,
                response_deserializer=api__pb2.RevokeConsentResp.FromString,
                _registered_method=True)


class DexServicer:
    """Dex represents the dex gRPC service.
    """

    def GetClient(self, request, context):
        """GetClient gets a client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateClient(self, request, context):
        """CreateClient creates a client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClient(self, request, context):
        """UpdateClient updates an existing client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteClient(self, request, context):
        """DeleteClient deletes the provided client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClients(self, request, context):
        """ListClients lists all client entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePassword(self, request, context):
        """CreatePassword creates a password.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePassword(self, request, context):
        """UpdatePassword modifies existing password.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePassword(self, request, context):
        """DeletePassword deletes the password.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPasswords(self, request, context):
        """ListPassword lists all password entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConnector(self, request, context):
        """CreateConnector creates a connector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConnector(self, request, context):
        """UpdateConnector modifies existing connector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConnector(self, request, context):
        """DeleteConnector deletes the connector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnectors(self, request, context):
        """ListConnectors lists all connector entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """GetVersion returns version information of the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiscovery(self, request, context):
        """GetDiscovery returns discovery information of the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRefresh(self, request, context):
        """ListRefresh lists all the refresh token entries for a particular user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeRefresh(self, request, context):
        """RevokeRefresh revokes the refresh token for the provided user-client pair.

        Note that each user-client pair can have only one refresh token at a time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPassword(self, request, context):
        """VerifyPassword returns whether a password matches a hash for a specific email or not.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthSession(self, request, context):
        """GetAuthSession returns an auth session by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuthSessions(self, request, context):
        """ListAuthSessions lists auth sessions, optionally filtered by user and connector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAuthSession(self, request, context):
        """DeleteAuthSession deletes an auth session and revokes associated refresh tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateSessionsByConnector(self, request, context):
        """TerminateSessionsByConnector terminates all sessions for a connector and revokes associated refresh tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateSessionsByUser(self, request, context):
        """TerminateSessionsByUser terminates all sessions for a user and revokes associated refresh tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserIdentity(self, request, context):
        """GetUserIdentity returns a user identity by user and connector ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserIdentities(self, request, context):
        """ListUserIdentities lists all user identities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserIdentity(self, request, context):
        """DeleteUserIdentity performs a full data purge for GDPR compliance: deletes the identity,
        auth session, refresh tokens, and offline sessions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetMFA(self, request, context):
        """ResetMFA clears all MFA secrets and WebAuthn credentials for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMFADevices(self, request, context):
        """ListMFADevices lists registered MFA authenticators for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWebAuthnCredential(self, request, context):
        """DeleteWebAuthnCredential deletes a specific WebAuthn credential.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMFASecret(self, request, context):
        """DeleteMFASecret deletes a specific MFA authenticator and its associated WebAuthn credentials.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeConsent(self, request, context):
        """RevokeConsent revokes consent for a specific client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClient,
                    request_deserializer=api__pb2.GetClientReq.FromString,
                    response_serializer=api__pb2.GetClientResp.SerializeToString,
            ),
            'CreateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClient,
                    request_deserializer=api__pb2.CreateClientReq.FromString,
                    response_serializer=api__pb2.CreateClientResp.SerializeToString,
            ),
            'UpdateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClient,
                    request_deserializer=api__pb2.UpdateClientReq.FromString,
                    response_serializer=api__pb2.UpdateClientResp.SerializeToString,
            ),
            'DeleteClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteClient,
                    request_deserializer=api__pb2.DeleteClientReq.FromString,
                    response_serializer=api__pb2.DeleteClientResp.SerializeToString,
            ),
            'ListClients': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClients,
                    request_deserializer=api__pb2.ListClientReq.FromString,
                    response_serializer=api__pb2.ListClientResp.SerializeToString,
            ),
            'CreatePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePassword,
                    request_deserializer=api__pb2.CreatePasswordReq.FromString,
                    response_serializer=api__pb2.CreatePasswordResp.SerializeToString,
            ),
            'UpdatePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePassword,
                    request_deserializer=api__pb2.UpdatePasswordReq.FromString,
                    response_serializer=api__pb2.UpdatePasswordResp.SerializeToString,
            ),
            'DeletePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePassword,
                    request_deserializer=api__pb2.DeletePasswordReq.FromString,
                    response_serializer=api__pb2.DeletePasswordResp.SerializeToString,
            ),
            'ListPasswords': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPasswords,
                    request_deserializer=api__pb2.ListPasswordReq.FromString,
                    response_serializer=api__pb2.ListPasswordResp.SerializeToString,
            ),
            'CreateConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConnector,
                    request_deserializer=api__pb2.CreateConnectorReq.FromString,
                    response_serializer=api__pb2.CreateConnectorResp.SerializeToString,
            ),
            'UpdateConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConnector,
                    request_deserializer=api__pb2.UpdateConnectorReq.FromString,
                    response_serializer=api__pb2.UpdateConnectorResp.SerializeToString,
            ),
            'DeleteConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConnector,
                    request_deserializer=api__pb2.DeleteConnectorReq.FromString,
                    response_serializer=api__pb2.DeleteConnectorResp.SerializeToString,
            ),
            'ListConnectors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectors,
                    request_deserializer=api__pb2.ListConnectorReq.FromString,
                    response_serializer=api__pb2.ListConnectorResp.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=api__pb2.VersionReq.FromString,
                    response_serializer=api__pb2.VersionResp.SerializeToString,
            ),
            'GetDiscovery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiscovery,
                    request_deserializer=api__pb2.DiscoveryReq.FromString,
                    response_serializer=api__pb2.DiscoveryResp.SerializeToString,
            ),
            'ListRefresh': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRefresh,
                    request_deserializer=api__pb2.ListRefreshReq.FromString,
                    response_serializer=api__pb2.ListRefreshResp.SerializeToString,
            ),
            'RevokeRefresh': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeRefresh,
                    request_deserializer=api__pb2.RevokeRefreshReq.FromString,
                    response_serializer=api__pb2.RevokeRefreshResp.SerializeToString,
            ),
            'VerifyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPassword,
                    request_deserializer=api__pb2.VerifyPasswordReq.FromString,
                    response_serializer=api__pb2.VerifyPasswordResp.SerializeToString,
            ),
            'GetAuthSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthSession,
                    request_deserializer=api__pb2.GetAuthSessionReq.FromString,
                    response_serializer=api__pb2.GetAuthSessionResp.SerializeToString,
            ),
            'ListAuthSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuthSessions,
                    request_deserializer=api__pb2.ListAuthSessionsReq.FromString,
                    response_serializer=api__pb2.ListAuthSessionsResp.SerializeToString,
            ),
            'DeleteAuthSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAuthSession,
                    request_deserializer=api__pb2.DeleteAuthSessionReq.FromString,
                    response_serializer=api__pb2.DeleteAuthSessionResp.SerializeToString,
            ),
            'TerminateSessionsByConnector': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateSessionsByConnector,
                    request_deserializer=api__pb2.TerminateSessionsByConnectorReq.FromString,
                    response_serializer=api__pb2.TerminateSessionsByConnectorResp.SerializeToString,
            ),
            'TerminateSessionsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateSessionsByUser,
                    request_deserializer=api__pb2.TerminateSessionsByUserReq.FromString,
                    response_serializer=api__pb2.TerminateSessionsByUserResp.SerializeToString,
            ),
            'GetUserIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserIdentity,
                    request_deserializer=api__pb2.GetUserIdentityReq.FromString,
                    response_serializer=api__pb2.GetUserIdentityResp.SerializeToString,
            ),
            'ListUserIdentities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserIdentities,
                    request_deserializer=api__pb2.ListUserIdentitiesReq.FromString,
                    response_serializer=api__pb2.ListUserIdentitiesResp.SerializeToString,
            ),
            'DeleteUserIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserIdentity,
                    request_deserializer=api__pb2.DeleteUserIdentityReq.FromString,
                    response_serializer=api__pb2.DeleteUserIdentityResp.SerializeToString,
            ),
            'ResetMFA': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetMFA,
                    request_deserializer=api__pb2.ResetMFAReq.FromString,
                    response_serializer=api__pb2.ResetMFAResp.SerializeToString,
            ),
            'ListMFADevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMFADevices,
                    request_deserializer=api__pb2.ListMFADevicesReq.FromString,
                    response_serializer=api__pb2.ListMFADevicesResp.SerializeToString,
            ),
            'DeleteWebAuthnCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWebAuthnCredential,
                    request_deserializer=api__pb2.DeleteWebAuthnCredentialReq.FromString,
                    response_serializer=api__pb2.DeleteWebAuthnCredentialResp.SerializeToString,
            ),
            'DeleteMFASecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMFASecret,
                    request_deserializer=api__pb2.DeleteMFASecretReq.FromString,
                    response_serializer=api__pb2.DeleteMFASecretResp.SerializeToString,
            ),
            'RevokeConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeConsent,
                    request_deserializer=api__pb2.RevokeConsentReq.FromString,
                    response_serializer=api__pb2.RevokeConsentResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.Dex', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.Dex', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dex:
    """Dex represents the dex gRPC service.
    """

    @staticmethod
    def GetClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/GetClient',
            api__pb2.GetClientReq.SerializeToString,
            api__pb2.GetClientResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/CreateClient',
            api__pb2.CreateClientReq.SerializeToString,
            api__pb2.CreateClientResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/UpdateClient',
            api__pb2.UpdateClientReq.SerializeToString,
            api__pb2.UpdateClientResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/DeleteClient',
            api__pb2.DeleteClientReq.SerializeToString,
            api__pb2.DeleteClientResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ListClients',
            api__pb2.ListClientReq.SerializeToString,
            api__pb2.ListClientResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/CreatePassword',
            api__pb2.CreatePasswordReq.SerializeToString,
            api__pb2.CreatePasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/UpdatePassword',
            api__pb2.UpdatePasswordReq.SerializeToString,
            api__pb2.UpdatePasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/DeletePassword',
            api__pb2.DeletePasswordReq.SerializeToString,
            api__pb2.DeletePasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPasswords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ListPasswords',
            api__pb2.ListPasswordReq.SerializeToString,
            api__pb2.ListPasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/CreateConnector',
            api__pb2.CreateConnectorReq.SerializeToString,
            api__pb2.CreateConnectorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/UpdateConnector',
            api__pb2.UpdateConnectorReq.SerializeToString,
            api__pb2.UpdateConnectorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/DeleteConnector',
            api__pb2.DeleteConnectorReq.SerializeToString,
            api__pb2.DeleteConnectorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConnectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ListConnectors',
            api__pb2.ListConnectorReq.SerializeToString,
            api__pb2.ListConnectorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/GetVersion',
            api__pb2.VersionReq.SerializeToString,
            api__pb2.VersionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiscovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/GetDiscovery',
            api__pb2.DiscoveryReq.SerializeToString,
            api__pb2.DiscoveryResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRefresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ListRefresh',
            api__pb2.ListRefreshReq.SerializeToString,
            api__pb2.ListRefreshResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeRefresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/RevokeRefresh',
            api__pb2.RevokeRefreshReq.SerializeToString,
            api__pb2.RevokeRefreshResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/VerifyPassword',
            api__pb2.VerifyPasswordReq.SerializeToString,
            api__pb2.VerifyPasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/GetAuthSession',
            api__pb2.GetAuthSessionReq.SerializeToString,
            api__pb2.GetAuthSessionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuthSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ListAuthSessions',
            api__pb2.ListAuthSessionsReq.SerializeToString,
            api__pb2.ListAuthSessionsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAuthSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/DeleteAuthSession',
            api__pb2.DeleteAuthSessionReq.SerializeToString,
            api__pb2.DeleteAuthSessionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateSessionsByConnector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/TerminateSessionsByConnector',
            api__pb2.TerminateSessionsByConnectorReq.SerializeToString,
            api__pb2.TerminateSessionsByConnectorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateSessionsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/TerminateSessionsByUser',
            api__pb2.TerminateSessionsByUserReq.SerializeToString,
            api__pb2.TerminateSessionsByUserResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/GetUserIdentity',
            api__pb2.GetUserIdentityReq.SerializeToString,
            api__pb2.GetUserIdentityResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserIdentities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ListUserIdentities',
            api__pb2.ListUserIdentitiesReq.SerializeToString,
            api__pb2.ListUserIdentitiesResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/DeleteUserIdentity',
            api__pb2.DeleteUserIdentityReq.SerializeToString,
            api__pb2.DeleteUserIdentityResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetMFA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ResetMFA',
            api__pb2.ResetMFAReq.SerializeToString,
            api__pb2.ResetMFAResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMFADevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/ListMFADevices',
            api__pb2.ListMFADevicesReq.SerializeToString,
            api__pb2.ListMFADevicesResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWebAuthnCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/DeleteWebAuthnCredential',
            api__pb2.DeleteWebAuthnCredentialReq.SerializeToString,
            api__pb2.DeleteWebAuthnCredentialResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMFASecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/DeleteMFASecret',
            api__pb2.DeleteMFASecretReq.SerializeToString,
            api__pb2.DeleteMFASecretResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Dex/RevokeConsent',
            api__pb2.RevokeConsentReq.SerializeToString,
            api__pb2.RevokeConsentResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
