site_name: 'Airframe'
site_description: 'Hangar''s Crossplane-based service catalog'

nav:
  - Home: index.md
  - User guide:
      - Overview: user/README.md
      - Quickstart: user/quickstart.md
      - 'Quickstart part 2: a database': user/quickstart-flight-api.md
      - Skyport demo system: user/skyport-demo.md
      - Decommissioning an app: user/decommission-app.md
  - Admin guide:
      - Overview: admin/README.md
      - Architecture: admin/architecture.md

plugins:
  - techdocs-core
