site_name: 'Airframe'
site_description: 'Hangar''s Crossplane-based service catalog'

nav:
  - Home: index.md
  - User guide:
      - Overview: user/README.md
      - Quickstart: user/quickstart.md
      - Skyport demo system: user/skyport-demo.md
  - Admin guide:
      - Overview: admin/README.md
      - Architecture: admin/architecture.md

plugins:
  - techdocs-core
