#!/usr/bin/env python3
"""Tier 2 domain-rename twin generator (catalog.idp.io -> catalog.hangar.io).

    tools/gen_hangar_twins.py            regenerate every twin from its base
    tools/gen_hangar_twins.py --check    exit 1 if any twin differs from its base (CI)

A twin is any compositions/<type>-hangar/composition.yaml (and xrds/<type>.hangar.yaml).
Twins are GENERATED, never hand-edited: they drifted from their bases three times in one day
(2026-09-30) when a base fix never reached its copy.

Composition twin = base with ONLY its own identity changed (metadata.name and
compositeTypeRef.apiVersion). Every other catalog.idp.io in a composition is a deliberate reference
to ANOTHER type (e.g. the TektonCICD child, old-group ExtraResources lookups) and must not flip.
XRD twin = base with the group replaced throughout (an XRD only names its own group).
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OLD, NEW = "catalog.idp.io", "catalog.hangar.io"

COMP_HEADER = (
    "# TIER 2 MIGRATION TWIN of compositions/{t}/composition.yaml - GENERATED by\n"
    "# tools/gen_hangar_twins.py, never hand-edit. Identical pipeline logic; only the composite's own\n"
    "# identity (metadata.name, compositeTypeRef.apiVersion) differs. See memory\n"
    "# project_tier2_domain_rename_plan.md.\n"
)
XRD_HEADER = (
    "# TIER 2 MIGRATION TWIN of xrds/{t}.yaml - GENERATED by tools/gen_hangar_twins.py, never hand-edit.\n"
    "# Identical schema, group only differs (catalog.hangar.io vs catalog.idp.io). Coexists with the\n"
    "# old-group XRD during migration; delete the old one once every live XR has migrated. See memory\n"
    "# project_tier2_domain_rename_plan.md.\n"
)

NAME_RE = re.compile(r"^  name: (\S+)\." + re.escape(OLD) + r"$", re.M)
CTR_RE = re.compile(r"^(    apiVersion: )" + re.escape(OLD) + r"(/v1alpha1\n    kind: )", re.M)


def twin_composition(base: str, t: str) -> str:
    out, n1 = NAME_RE.subn(lambda m: f"  name: {m.group(1)}.{NEW}", base, count=1)
    out, n2 = CTR_RE.subn(lambda m: f"{m.group(1)}{NEW}{m.group(2)}", out, count=1)
    if n1 != 1 or n2 != 1:
        raise SystemExit(f"{t}: expected exactly one metadata.name and one compositeTypeRef to flip, got {n1}/{n2}")
    return COMP_HEADER.format(t=t) + out


def twin_xrd(base: str, t: str) -> str:
    if OLD not in base:
        raise SystemExit(f"{t}: base XRD does not mention {OLD}")
    return XRD_HEADER.format(t=t) + base.replace(OLD, NEW)


def targets():
    for d in sorted((ROOT / "compositions").glob("*-hangar")):
        t = d.name[: -len("-hangar")]
        base = ROOT / "compositions" / t / "composition.yaml"
        if not base.exists():
            raise SystemExit(f"{d.name}: no base compositions/{t}/composition.yaml")
        yield d / "composition.yaml", twin_composition(base.read_text(), t)
        xbase = ROOT / "xrds" / f"{t}.yaml"
        xtwin = ROOT / "xrds" / f"{t}.hangar.yaml"
        if xtwin.exists():
            yield xtwin, twin_xrd(xbase.read_text(), t)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    stale = []
    count = 0
    for path, want in targets():
        count += 1
        have = path.read_text() if path.exists() else ""
        if have != want:
            stale.append(path)
            if not a.check:
                path.write_text(want)
    if count == 0:
        print("FAIL: found no twins - refusing to report success on an empty set")
        return 1
    rel = [str(p.relative_to(ROOT)) for p in stale]
    if a.check:
        if rel:
            print("FAIL: twins drifted from their bases - run tools/gen_hangar_twins.py and commit:\n  " + "\n  ".join(rel))
            return 1
        print(f"ok: {count} twin files match their bases")
        return 0
    print(f"regenerated {len(rel)} of {count} twin files" + ("".join("\n  " + r for r in rel)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
