#!/usr/bin/env python3
"""Generate compositions/<dir>/AGENTS.md for every XRD from its xrds/<kind>.meta.yaml sidecar (review A7).

One short, kind-specific briefing per composition: how the kind is requested, what it produces and where
each object comes from, its conditions, how to verify a live XR, known failures, and the editing rules and
gotchas for that composition (`agentNotes` in the sidecar). Everything comes from the sidecar, so the file
cannot disagree with the contract bundle or airframe-verify.

    python3 tools/gen_component_agents.py           # write
    python3 tools/gen_component_agents.py --check   # CI: exit 1 if any file is stale
"""
import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sidecars import ROOT, load_sidecars  # noqa: E402

HOW = {
    "component": "A `components[]` entry in an app's values file; the airframe-application chart renders the XR in the app's namespace. Wire it into the app with `env[].fromComponent` (never hand-write the derived names).",
    "target": "A stand-alone XR request in the tenants repo (`tenants/<app>/xr-requests/`), or composed by a function app with `spec.target.enabled`. See docs/user/cloud-targets.md.",
    "bootstrap": "A Backstage template or an XR request in the dev cluster's tenants repo; it onboards the app onto the dev cluster.",
    "environment": "An XR request in the dev cluster's tenants repo, one per app and Flight environment; it writes the target cluster's tenants files.",
    "platform": "Composed by other kinds; not requested directly.",
    "observability": "Rendered by the airframe-application chart from an app's values file; not requested directly.",
}


def composition_dirs():
    out = {}
    for f in sorted((ROOT / "compositions").glob("*/composition.yaml")):
        if f.parent.name.startswith("_") or f.parent.name.endswith("-hangar"):
            continue
        for d in yaml.safe_load_all(f.read_text()):
            if d and d.get("kind") == "Composition":
                out[d["spec"]["compositeTypeRef"]["kind"]] = f.parent
    return out


def render(key, sc, comp_dir):
    kind = sc["kind"]
    lines = [f"# {kind}", "",
             "<!-- GENERATED by tools/gen_component_agents.py from "
             f"xrds/{sc['_file']}; edit the sidecar, not this file. -->", "",
             sc["summary"], "",
             "## How it is requested", "", HOW[sc["role"]], ""]
    outs = sc.get("outputs") or {}
    if outs:
        lines += ["## Outputs", ""]
        for name, o in outs.items():
            if o["kind"] == "secretKeyRef":
                where = f"Secret `{o['secret']}`, key `{o['key']}`"
            elif o["kind"] == "configMapKeyRef":
                where = f"ConfigMap `{o['configMap']}`, key `{o['key']}`"
            else:
                where = f"`{o['value']}`"
            lines.append(f"- `{name}`: {where}." + (f" {o['description'].strip()}" if o.get("description") else ""))
        lines.append("")
    srcs = sc.get("sources") or []
    if srcs:
        lines += ["## Where named objects come from", ""]
        for s in srcs:
            obj = s["object"]
            how = {"composition": "composed by this composition", "operator": f"created by an operator from the composed {s.get('from', {}).get('kind')}",
                   "crossplane": f"written by Crossplane from the {s.get('from', {}).get('kind')}'s connection details",
                   "function": "rendered by the composition function"}[s["createdBy"]]
            when = f" (when `{s['when']['field']}` is `{s['when'].get('equals', s['when'].get('in'))}`)" if s.get("when") else ""
            lines.append(f"- {obj['kind']} `{obj['name']}`: {how}{when}.")
        lines.append("")
    conds = sc.get("conditions") or []
    if conds:
        lines += ["## Conditions", "", "Besides Crossplane's Ready and Synced. Reasons are a closed set:", ""]
        for c in conds:
            lines.append(f"- `{c['type']}`: " + ", ".join(f"`{r['reason']}` ({r['status']})" for r in c["reasons"]) + ".")
        lines.append("")
    lines += ["## Verify a live XR", "", "```", f"tools/airframe-verify {key} <namespace>/<name> [--context CTX]", "```", "",
              "Read-only. Steps, after the implicit `xr-synced` check:", ""]
    for v in sc.get("verify") or []:
        when = f" Only when `{v['when']['field']}` is `{v['when'].get('equals', v['when'].get('in'))}`." if v.get("when") else ""
        lines.append(f"- `{v['id']}` ({v['run']['kind']}): {' '.join(v['check'].split())}{when}")
    lines.append("")
    kf = sc.get("knownFailures") or []
    if kf:
        lines += ["## Known failures", ""]
        for k in kf:
            lines.append(f"- `{k['id']}` ({k['condition']}=False): {' '.join(k['meaning'].split())} {' '.join(k['hint'].split())}")
        lines.append("")
    lines += ["## Editing this composition", ""]
    if comp_dir is not None and (comp_dir / "templates").is_dir():
        rel = comp_dir.relative_to(ROOT)
        lines += [f"- Edit `{rel}/templates/`, never the inline blocks in `composition.yaml`: `python3 tools/build-compositions {comp_dir.name}` splices them.",
                  f"- `python3 tools/test_compositions.py --update {comp_dir.name}` regenerates `example/expected/`; review that diff like code, it is the behaviour change.",
                  "- `python3 tools/test_sidecars.py` fails if a template change breaks a name this sidecar promises."]
        shared = sorted(p.name for p in (comp_dir / "templates").rglob("*") if p.is_symlink())
        if shared:
            lines.append(f"- Shared with other compositions (symlinks into `compositions/_shared/`): {', '.join(f'`{s}`' for s in shared)}.")
    for n in sc.get("agentNotes") or []:
        lines.append(f"- {n}")
    lines += ["", f"Contract: `tools/airframe-capabilities verify {key}`; schema: `xrds/{sc['_file'].replace('.meta.yaml', '.yaml')}`.", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    dirs = composition_dirs()
    stale = []
    for key, sc in sorted(load_sidecars().items()):
        comp_dir = dirs.get(sc["kind"])
        if comp_dir is None:
            stale.append(f"{sc['kind']}: no composition directory")
            continue
        target = comp_dir / "AGENTS.md"
        text = render(key, sc, comp_dir)
        if a.check:
            if not target.exists() or target.read_text() != text:
                stale.append(str(target.relative_to(ROOT)))
        else:
            target.write_text(text)
    if stale:
        print("stale (run python3 tools/gen_component_agents.py): " + ", ".join(stale))
        return 1
    print(f"ok: {len(load_sidecars())} compositions/*/AGENTS.md {'match' if a.check else 'written from'} their sidecars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
